# Generated by Django 4.1.1 on 2022-10-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tarea_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tarea',
            name='lugar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
